"""Minimal unified-diff application for critic proposals.

Proposals store diffs generated by difflib.unified_diff with a/<path> and
b/<path> headers. This applier is deliberately strict: context and deletion
lines must match the target exactly, otherwise it raises — a stale proposal
must fail loudly, never fuzz-apply.
"""

from __future__ import annotations

import re
from pathlib import Path

_HUNK_RE = re.compile(r"^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@")


class DiffError(Exception):
    pass


def diff_target_path(diff: str) -> str:
    """The b/<path> a diff writes to, e.g. 'prompts/score.md'."""
    for line in diff.splitlines():
        if line.startswith("+++ "):
            target = line[4:].split("\t")[0].strip()
            return target[2:] if target.startswith("b/") else target
    raise DiffError("diff has no +++ header")


def apply_unified_diff(diff: str, original: str) -> str:
    """Apply one single-file unified diff to `original`, returning new text."""
    src = original.splitlines(keepends=True)
    out: list[str] = []
    pos = 0  # index into src
    lines = diff.splitlines(keepends=True)
    i = 0
    saw_hunk = False
    while i < len(lines):
        line = lines[i]
        m = _HUNK_RE.match(line)
        if not m:
            i += 1
            continue
        saw_hunk = True
        old_start = int(m.group(1))
        # copy unchanged region before the hunk
        hunk_src_index = old_start - 1 if old_start > 0 else 0
        if hunk_src_index < pos:
            raise DiffError("overlapping or out-of-order hunks")
        out.extend(src[pos:hunk_src_index])
        pos = hunk_src_index
        i += 1
        while i < len(lines) and not _HUNK_RE.match(lines[i]):
            hline = lines[i]
            if hline.startswith("--- ") or hline.startswith("+++ "):
                break
            tag, body = hline[:1], hline[1:]
            if tag == " ":
                if pos >= len(src) or src[pos] != body:
                    raise DiffError(f"context mismatch at source line {pos + 1}")
                out.append(src[pos])
                pos += 1
            elif tag == "-":
                if pos >= len(src) or src[pos] != body:
                    raise DiffError(f"deletion mismatch at source line {pos + 1}")
                pos += 1
            elif tag == "+":
                out.append(body)
            elif hline.startswith("\\"):  # "\ No newline at end of file"
                if out and out[-1].endswith("\n"):
                    out[-1] = out[-1][:-1]
            else:
                raise DiffError(f"unexpected diff line: {hline!r}")
            i += 1
    if not saw_hunk:
        raise DiffError("diff contains no hunks")
    out.extend(src[pos:])
    return "".join(out)


def apply_diff_to_file(diff: str, root: Path) -> Path:
    """Apply a proposal diff to root/<target>; returns the changed path."""
    rel = diff_target_path(diff)
    target = (root / rel).resolve()
    if not target.is_relative_to(root.resolve()):
        raise DiffError(f"diff target escapes root: {rel}")
    new_text = apply_unified_diff(diff, target.read_text(encoding="utf-8"))
    target.write_text(new_text, encoding="utf-8")
    return target
